/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.tweetModel;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import ngram.NGram;

/**
 *
 * @author Nancy
 */
public class viewNGram extends javax.swing.JFrame {
    private Scanner scan;
    private static DefaultTableModel model;
  // private static ArrayList<NGram> tweets= ngram.NGramDriver.getNgramlist(); 
    /**
     * Creates new form viewTweets
     */
    public viewNGram() {
        
        initComponents();
        insertTweets(ngram.NGramDriver.getNgramlist());
//        insertTweetsList(tweets);
    }

    
    private void insertTweets(ArrayList<NGram> tweets){
       model = (DefaultTableModel)tweetTable.getModel();
       model.setRowCount(0);
       // NGram[] t;
       String t;
       int i;
   		for(int num = 0; num < tweets.size(); num++){
                   t= tweets.get(num).getTweet();
                   i= tweets.get(num).getFrequency();
                         model.addRow(new Object[]{t,i});
                         
                        
   		}
       
           
        
    }
    
    private void insertTweetsList(ArrayList<tweetModel> tweets){
        model = (DefaultTableModel)tweetTable.getModel();
       model.setRowCount(0);
        
         NGram[] t = new NGram[tweets.size()];
   		for(int num = 0; num < tweets.size(); num++){
   		//	t[num] = tweets.get(num);
                         model.addRow(new Object[]{t});
   		}
    }
    
    private void open(){
        try {
            scan = new Scanner(new File("src\\tweets.txt"));
            System.out.println("It is working.....");
        } catch (FileNotFoundException ex) {
            System.out.println("Not working.");
        }
    }
    
    private List<String> read(){
        List<String> lines = new ArrayList<>();
        
        open();
        scan.reset();
        while(scan.hasNextLine()){
            lines.add(scan.nextLine());
        }
        
        return lines;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tweetTable = new javax.swing.JTable();

        tweetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tweet Message", "Frequency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tweetTable);
        if (tweetTable.getColumnModel().getColumnCount() > 0) {
            tweetTable.getColumnModel().getColumn(0).setResizable(false);
            tweetTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewNGram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewNGram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewNGram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewNGram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new viewNGram().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tweetTable;
    // End of variables declaration//GEN-END:variables
}
